website:
  title: "Proyecto de datos sobre deportaciones"
  # announcement:
  #   icon: info-circle
  #   dismissable: true
  #   content: "No prevemos actualizaciones de datos antes de que finalice el cierre del gobierno federal."
  #   type: primary
  #   position: below-navbar
  navbar:
    left:
      - text: "Datos"
        menu:
          - text: "Descripción general"
            href: data.qmd
          - text: "---"
          - text: "Por agencia"
          - text: "ICE: Servicio de Inmigración y Control de Aduanas"
            href: data/ice.qmd
          - text: "CBP: Oficina de Aduanas y Protección Fronteriza"
            href: data/cbp.qmd
          - text: "EOIR: Oficina Ejecutiva de Revisión de Casos de Inmigración (Tribunales de Inmigración)"
            href: data/eoir.qmd
          - text: "EOUSA: Oficina Ejecutiva de Fiscales Federales (Procesamientos de Inmigración)"
            href: data/eousa.qmd
          - text: "---"
          - text: "Informes de agencias"
            href: data/reports.qmd
      - text: "Documentación"
        menu:
          - text: "Guía de datos"
            href: guide.qmd
          - text: "---"
          - text: "Por agencia"
          - text: "ICE: Servicio de Inmigración y Control de Aduanas"
            href: docs/ice.qmd
          - text: "CBP: Oficina de Aduanas y Protección Fronteriza"
            href: docs/cbp.qmd
          - text: "EOIR: Oficina Ejecutiva de Revisión de Casos de Inmigración (Tribunales de Inmigración)"
            href: docs/eoir.qmd
          - text: "EOUSA: Oficina Ejecutiva de Fiscales Federales (Procesamientos de Inmigración)"
            href: docs/eousa.qmd
          - text: "---"
          - text: "Solicitudes de la Ley de Libertad de Información"
            href: foia.qmd
      - text: Herramientas
        href: tools.qmd
      - text: Noticias
        href: news.qmd
      - text: Acerca de
        href: about.qmd
      - text: Relacionados
        href: related.qmd
  sidebar:
    - title: "Datos"
      collapse-level: 3
      style: "docked"
      contents:
        - section: "Datos"
          contents:
            - text: "Descripción general"
              href: data.qmd
            - section: "Por agencia"
              contents: 
                - text: "ICE: Servicio de Inmigración y Control de Aduanas"
                  href: data/ice.qmd
                - text: "CBP: Oficina de Aduanas y Protección Fronteriza"
                  href: data/cbp.qmd
                - text: "EOIR: Oficina Ejecutiva de Revisión de Casos de Inmigración (Tribunales de Inmigración)"
                  href: data/eoir.qmd
                - text: "EOUSA: Oficina Ejecutiva de Fiscales Federales (Procesamientos de Inmigración)"
                  href: data/eousa.qmd
            - text: "Informes de agencias"
              href: data/reports.qmd
    - title: "Documentación"
      collapse-level: 3
      style: "docked"
      contents:
        - section: "Documentación"
          contents:
            - text: "Guía de datos"
              href: guide.qmd
            - section: "Por agencia"
              contents: 
                - section: "ICE: Servicio de Inmigración y Control de Aduanas"
                  href: docs/ice.qmd
                  contents:
                    - text: "Libro de códigos"
                      href: docs/ice/codebook.qmd
                    - text: "Documentos"
                      href: docs/ice/documents.qmd
                    - text: "Instalaciones"
                      href: docs/ice/facilities.qmd
                - section: "CBP: Oficina de Aduanas y Protección Fronteriza"
                  href: docs/cbp.qmd
                  contents:
                    - text: "Documentos"
                      href: docs/cbp/documents.qmd
                - section: "EOIR: Oficina Ejecutiva de Revisión de Casos de Inmigración (Tribunales de Inmigración)"
                  href: docs/eoir.qmd
                  contents:
                    - text: "Libro de códigos"
                      href: docs/eoir/codebook.qmd
                    - text: "Documentos"
                      href: docs/eoir/documents.qmd
                - section: "EOUSA: Oficina Ejecutiva de Fiscales Federales (Procesamientos de Inmigración)"
                  href: docs/eousa.qmd
                  contents:
                    - text: "Documentos"
                      href: docs/eousa/documents.qmd
            - text: "Solicitudes de la Ley de Libertad de Información"
              href: foia.qmd
  page-footer:
    center: "Con licencia [CC-0](https://creativecommons.org/publicdomain/zero/1.0/) (sin derechos reservados)"

lang: es
