project:
  type: website
  resources:
    - img
    - foia
    - tmp

website:
  search: true
  google-analytics:
    tracking-id: "G-FL9SCY5B31"
    anonymize-ip: true
    storage: none

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css:
    - styles.css
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css
    toc: true
    include-after-body: navbar-reorder.js

execute:
  echo: false
  warning: false
  message: false
  error: false

babelquarto:
  # languagelinks: navbar
  languagecodes:
  - name: en
    text: "English"
  - name: es
    text: "Espa√±ol"
  mainlanguage: 'en'
  languages: ['es']

title-es: Proyecto de datos sobre deportaciones
lang: en
