website:
  title: "Deportation Data Project"
  # announcement:
  #   icon: info-circle
  #   dismissable: true
  #   content: "We do not expect any data updates before the federal government shutdown ends."
  #   type: primary
  # position: below-navbar
  navbar:
    left:
      - text: "Data"
        menu:
          - text: "Overview"
            href: data.qmd
          - text: "---"
          - text: "By agency"
          - text: "ICE: Immigration and Customs Enforcement"
            href: data/ice.qmd
          - text: "CBP: Customs and Border Protection"
            href: data/cbp.qmd
          - text: "EOIR: Executive Office for Immigration Review (Immigration Courts)"
            href: data/eoir.qmd
          - text: "EOUSA: Executive Office for United States Attorneys (Immigration Prosecutions)"
            href: data/eousa.qmd
          - text: "---"
          - text: "Agency reports"
            href: data/reports.qmd
      - text: "Documentation"
        menu:
          - text: "Data guide"
            href: guide.qmd
          - text: "---"
          - text: "By agency"
          - text: "ICE: Immigration and Customs Enforcement"
            href: docs/ice.qmd
          - text: "CBP: Customs and Border Protection"
            href: docs/cbp.qmd
          - text: "EOIR: Executive Office for Immigration Review (Immigration Courts)"
            href: docs/eoir.qmd
          - text: "EOUSA: Executive Office for United States Attorneys (Immigration Prosecutions)"
            href: docs/eousa.qmd
          - text: "---"
          - text: "All agency documentation"
            href: docs/documents.qmd
          - text: "Freedom of Information Act requests"
            href: docs/foia.qmd
          - text: "Articles and reports using the data"
            href: docs/research.qmd
      - text: Tools
        href: tools.qmd
      - text: News
        href: news.qmd
      - text: About
        href: about.qmd
      - text: Related
        href: related.qmd
  sidebar:
    - title: "Data"
      collapse-level: 3
      style: "docked"
      contents:
        - section: "Data"
          contents:
            - text: "Overview"
              href: data.qmd
            - section: "By agency"
              contents: 
                - text: "ICE: Immigration and Customs Enforcement"
                  href: data/ice.qmd
                - text: "CBP: Customs and Border Protection"
                  href: data/cbp.qmd
                - text: "EOIR: Executive Office for Immigration Review (Immigration Courts)"
                  href: data/eoir.qmd
                - text: "EOUSA: Executive Office for United States Attorneys (Immigration Prosecutions)"
                  href: data/eousa.qmd
            - text: "Agency reports"
              href: data/reports.qmd
    - title: "Documentation"
      collapse-level: 3
      style: "docked"
      contents:
        - section: "Documentation"
          contents:
            - text: "Data guide"
              href: guide.qmd
            - section: "By agency"
              contents: 
                - section: "ICE: Immigration and Customs Enforcement"
                  href: docs/ice.qmd
                  contents:
                    - text: "Codebook"
                      href: docs/ice/codebook.qmd
                    - text: "Documents"
                      href: docs/ice/documents.qmd
                    - text: "Facilities"
                      href: docs/ice/facilities.qmd
                - text: "CBP: Customs and Border Protection"
                  href: docs/cbp.qmd
                  contents:
                    - text: "Documents"
                      href: docs/cbp/documents.qmd
                - text: "EOIR: Executive Office for Immigration Review (Immigration Courts)"
                  href: docs/eoir.qmd
                  contents:
                    - text: "Codebook"
                      href: docs/eoir/codebook.qmd
                    - text: "Documents"
                      href: docs/eoir/documents.qmd
                - text: "EOUSA: Executive Office for United States Attorneys (Immigration Prosecutions)"
                  href: docs/eousa.qmd
                  contents:
                    - text: "Documents"
                      href: docs/eousa/documents.qmd
            - text: "All agency documentation"
              href: docs/documents.qmd
            - text: "Freedom of Information Act requests"
              href: docs/foia.qmd
            - text: "Articles and reports using the data"
              href: docs/research.qmd
  page-footer:
    center: "Licensed [CC-0](https://creativecommons.org/publicdomain/zero/1.0/) (no rights reserved)"
lang: en
