name: daily R job to update metadata

on:
  schedule:
     - cron: '0 5 * * *' # every day at 05:00 UTC

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2

      - name: Run script
        run: Rscript _exclude/get_metadata.R

      - name: Commit data files 
        run: |
          set -e
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update data [skip ci] ($(date -u +"%Y-%m-%d %H:%M UTC"))"
            
            echo "Syncing with remote before push..."
            git pull --rebase origin main 

            git push
          else
            echo "No changes to commit"
          fi